version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=test
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/initdb.d:/docker-entrypoint-initdb.d

